concurrency: 5
development:
  pidfile: tmp/pids/sidekiq_development.pid
  logfile: log/sidekiq_development.log
staging:
  pidfile: /var/run/sidekiq_stating.pid
  logfile: log/sidekiq_staging.log
production:
  pidfile: /home/deployer/qna/shared/tmp/pids/sidekiq-0.pid
  logfile: /home/deployer/qna/shared/log/sidekiq_production.log
  concurrency: 50
